### ISSUE TITLE
Make a fabric compatibility for 1.21

### ISSUE THREAD

**Issue by Sharpnesse49** [justanoval/Lockable#7]

**Comment by Sharpnesse49** [comment]
Thats can add more player and its better with other mod compatibility.....

**Comment by justanoval** [comment]
Not totally sure what you mean by it can add more players. When it comes to other mod compatibility, most mods on Quilt work with Fabric, but some don't if they depend on Fabric-specific things.

Regardless, this is not something I _currently_ plan to do. My mods are going to be made on Quilt for the time being. If in the future there is reason for me to move away from Quilt, or I decide to put more of my time into mod development, then I can look into building to several modloaders.

**Comment by justanoval** [comment]
Given new developments and just general preference for future-proofing my mods, I'll be switching to Fabric. So I figured I'd let you know that'll be in #9! It'll take time though, as I have a lot going on in my life atm
